### ISSUE TITLE
Width calculation is off in IE10 >

### ISSUE THREAD

**Issue by velkommen** [JedWatson/react-input-autosize#6]
The MS-Clear icon destroys the width calculation on IE10 >
https://msdn.microsoft.com/en-us/library/windows/apps/hh465740.aspx

Is fixed with css-style: 

::-ms-clear {
        width : 0;
        height: 0;
  }

**Comment by JedWatson** [comment]
Thanks, any idea how to add that without including a .css file in the project?

**Comment by velkommen** [comment]
I guess a general css-fix is a bit hacky (and removing native browser functionality is probably not that good)
A better fix would be to find out if the user has the ::-ms-clear / ::-ms-reveal, and calculate the offset. Not sure how though :)

**Comment by ksmth** [comment]
There seems to be another issue with the width calculation in some instances. It's certainly not happening on the demo website, but I encountered the issue in a project. In order to make IE behave, I had to add the following style to the sizer:

```
-ms-overflow-style: -ms-autohiding-scrollbar;
```

You can see the effects here:
http://codepen.io/anon/pen/oxpdaE?editors=1111

Open the codepen console on the bottom left to see the `scrollWidth` property of the `sizer` element logged.

**Comment by JedWatson** [comment]
I *think* the IE Issues are fixed, if anyone can still reproduce them please open a new issue with details. Thanks!
