### ISSUE TITLE
Unknown prop `minWidth` on <input> tag. with react 15.2

### ISSUE THREAD

**Issue by Stupidism** [JedWatson/react-input-autosize#68]
```
warning.js:36 Warning: Unknown prop `minWidth` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

**Comment by hawkrives** [comment]
@stupidisum see #57

**Comment by stupidisum** [comment]
Can't agree 100% with @JedWatson. `minWidth passed down to input tag` causing `react unknown props warning` is a bug because minWidth is something `react-input-autosize` wants. However, other props which `react-input-autosize` doesn't wants passed down to is a problem of developers themselves or a bug of other libraries using `react-input-autosize`. So I insist on fixing this first and then considering a breaking change on `inputProps`.

**Comment by stupidisum** [comment]
@hawkrives Are you still on this?

**Comment by hawkrives** [comment]
@stupidisum No

**Comment by twoelevenjay** [comment]
Any movement on this? I was going to test your proposed fix @hawkrives, but for some reason I can not run the dev or build scripts in my environment for either react-select or react-input-autosize.

**Comment by JedWatson** [comment]
I just realised this has been resolved
